# Generated by Django 4.2.13 on 2024-05-13 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
    ]
