# Generated by Django 4.2.13 on 2024-05-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_customuser_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pin',
            field=models.CharField(max_length=4, null=True, verbose_name='ПИН-КОД'),
        ),
    ]
