# Generated by Django 4.2.13 on 2024-05-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_customuser_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(max_length=50, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='passport_issuer',
            field=models.CharField(max_length=100, verbose_name='Кем выдан паспорт'),
        ),
    ]
