# Generated by Django 4.2.13 on 2024-05-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_customuser_groups_customuser_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telegram',
            field=models.BooleanField(default=False, verbose_name='Telegram'),
        ),
    ]
