# Generated by Django 4.2.13 on 2024-05-31 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_customuser_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='input_attempts',
            field=models.IntegerField(default=0, verbose_name='Количество вводов'),
        ),
    ]
