# Generated by Django 4.2.13 on 2024-06-02 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_number', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Номер счета')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Баланс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='DepositCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название условия')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Процентная ставка')),
                ('period_in_months', models.IntegerField(verbose_name='Период в месяцах действия')),
                ('early_closure_allowed', models.BooleanField(default=False, verbose_name='Возможно ли закрыть досрочно')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Название')),
                ('monthly_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ежемесячная стоимость')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='your_bank.account', verbose_name='Номер счета')),
                ('name', models.CharField(max_length=100, verbose_name='Название организации')),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата открытия')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='your_bank.account', verbose_name='Номер счета')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='your_bank.depositcondition', verbose_name='Условия депозита')),
            ],
        ),
        migrations.CreateModel(
            name='DebitCard',
            fields=[
                ('card_number', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='Номер карты')),
                ('frozen', models.BooleanField(default=False, verbose_name='Заморожена')),
                ('expiration_date', models.CharField(max_length=5, verbose_name='Срок действия (MM/YY)')),
                ('cvv', models.CharField(max_length=3, verbose_name='CVV код')),
                ('pin_code', models.CharField(max_length=4, verbose_name='PIN код')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='your_bank.account', verbose_name='Номер счета')),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='your_bank.subscription', verbose_name='Условия')),
            ],
        ),
    ]
