# Generated by Django 4.2.13 on 2024-05-20 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('your_bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitcard',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='your_bank.subscription', verbose_name='Условия'),
        ),
    ]
