# Generated by Django 4.2.13 on 2024-06-03 23:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('your_bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID транзакции')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время транзакции')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transactions', to='your_bank.account', verbose_name='Счёт отправителя')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transactions', to='your_bank.account', verbose_name='Счёт получателя')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ATMTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID транзакции')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время транзакции')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], max_length=10, verbose_name='Тип транзакции')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='your_bank.account', verbose_name='Счёт')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
